name: xpensea
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: Unna
      fonts:
        - asset: assets/fonts/Unna-Bold.ttf
          weight: 700
        - asset: assets/fonts/Unna-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Unna-Italic.ttf
        - asset: assets/fonts/Unna-Regular.ttf
