name: xpensea
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: 3.22.2

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: 2.0.9
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.4
  onscreen_num_keyboard: ^1.0.4
  pinput: ^5.0.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  http: any
  flutter_dotenv: ^5.1.0
  minio_flutter: ^0.0.1
  geolocator: ^12.0.0
  geolocator_android: 4.5.5  
  ai_barcode_scanner: ^3.4.3

  lottie: ^3.1.2
  motion: ^1.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/lottie/
    - assets/images/
    - .env

  fonts:
    - family: Unna
      fonts:
        - asset: assets/fonts/Unna-Bold.ttf
          weight: 700
        - asset: assets/fonts/Unna-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Unna-Italic.ttf
          weight: 400
        - asset: assets/fonts/Unna-Regular.ttf
          weight: 400

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
