name: Flutter CI

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - prod
      - TestNihal
    
jobs:
  Android:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Java environment in order to build the Android app.
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12'
      
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter
      
      # Get flutter dependencies.
      - name: Get dependencies
        run: flutter pub get
        working-directory: xpensea
    
      

      
      
      # Build apk.
      - name: Build APK
        run: flutter build apk
        working-directory: xpensea
      
      # Upload generated apk to the artifacts.
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: xpensea/build/app/outputs/apk/release/app-release.apk

  Ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Get dependencies
        run: flutter pub get
        working-directory: xpensea
      

      
      - name: Build iOS
        run: flutter build ios --release --no-codesign
        working-directory: xpensea
